/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface MyTemplate {
        "afterSwipe": () => Promise<void>;
        "beforeSwipe": (enter: boolean, reveal: boolean) => Promise<boolean>;
        "hideContent": () => Promise<void>;
        "lazyLoadContent": () => Promise<void>;
        "revealContent": () => Promise<void>;
        /**
          * An example of a custom property
         */
        "value": string;
    }
}
declare global {
    interface HTMLMyTemplateElement extends Components.MyTemplate, HTMLStencilElement {
    }
    var HTMLMyTemplateElement: {
        prototype: HTMLMyTemplateElement;
        new (): HTMLMyTemplateElement;
    };
    interface HTMLElementTagNameMap {
        "my-template": HTMLMyTemplateElement;
    }
}
declare namespace LocalJSX {
    interface MyTemplate {
        "onSlideDidLoad"?: (event: CustomEvent<void>) => void;
        /**
          * An example of a custom property
         */
        "value"?: string;
    }
    interface IntrinsicElements {
        "my-template": MyTemplate;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "my-template": LocalJSX.MyTemplate & JSXBase.HTMLAttributes<HTMLMyTemplateElement>;
        }
    }
}
